### ISSUE TITLE
missing db

### ISSUE THREAD

**Issue by vesvello** [mchev/laravel-intranet#4]
Hi,

Im trying to check your project but db is missing.
Can you share the db?

thanks in advance

**Comment by mchev** [comment]
Hi,

The database problem is now fixed. Refer to the readme for installation.

**Comment by vesvello** [comment]
Thank you very much!

________________________________
De: mchev <notifications@github.com>
Enviado: sábado, 5 de septiembre de 2020 1:00 a. m.
Para: mchev/laravel-intranet <laravel-intranet@noreply.github.com>
CC: RAV <rav.1971@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [mchev/laravel-intranet] missing db (#4)


Hi,

The database problem is now fixed. Refer to the readme for installation.
